timezone: Europe/London
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
highlighter: pygments
encoding: utf-8
safe: false
lsi: false

baseurl: /
permalink: /:year/:month/:day/:title
url: http://gtranchedone.com
imagesurl: /assets/images/

title: "Gianluca Tranchedone"
description: "Gianluca's Personal Website"

author:
  name: "Gianluca Tranchedone"
  email: g.tranchedone@gmail.com
  github: gtranchedone
  twitter: gtranchedone
  facebook: gtranchedone
  google: +GianlucaTranchedone

paginate: 4

gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji