timezone: Europe/London
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
encoding: utf-8
pygments: true
safe: false
lsi: false

baseurl: /
permalink: /:year/:month/:day/:title
url: http://gtranchedone.com

title: Gianluca Tranchedone
description: "Gianluca's Personal Website"

author:
  name: Gianluca Tranchedone
  email: g.tranchedone@gmail.com
  github: gtranchedone
  twitter: gtranchedone
  facebook: gtranchedone
  google: +GianlucaTranchedone

paginate: 4

gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji