baseurl: /
permalink: /blog/:title
url: http://gtranchedone.com
name: Gianluca Tranchedone
description: "Gianluca's Personal Website"
timezone: Europe/London
markdown: redcarpet
encoding: utf-8
pygments: true
safe: true
lsi: false

gems:
  - jekyll-sitemap