timezone: Europe/London
markdown: redcarpet
redcarpet:
  extensions:
    - footnotes
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
highlighter: pygments
encoding: utf-8
safe: false
lsi: false

baseurl: /
permalink: /:year/:month/:day/:title
url: http://gtranchedone.com
imagesurl: /assets/images/
paginate: 4

title: "Gianluca Tranchedone"
description: "Gianluca's Personal Website"

collections:
  authors:
    output: true

gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji