timezone: Europe/London
markdown: redcarpet
redcarpet:
  extensions:
    - footnotes
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
highlighter: rouge
encoding: utf-8
safe: false
lsi: false

url: http://gtranchedone.com
baseurl: /

imagesurl: /assets/images/
permalink: /blog/:year/:month/:day/:title

paginate_path: /blog/page:num/
paginate: 5

title: "Gianluca Tranchedone"
description: "Gianluca's Personal Website"

collections:
  authors:
    output: true

gems:
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
